version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: order-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: order_service

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_service -d order_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: order-service

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/order_service
      DB_USERNAME: order_service
      DB_PASSWORD: order_service

    ports:
      - "8082:8082"

    restart: unless-stopped

volumes:
  postgres_data: